###
GET http://localhost/users
Content-Type: application/json
Accept: application/json

###
GET http://localhost/users/1
Accept: application/json

###
GET http://localhost/users/1/roles
Accept: application/json

###
GET http://localhost/users/2/roles
Accept: application/json

###
GET http://localhost/users/3/roles
Accept: application/json

###
GET http://localhost/departments
Accept: application/json

###
GET http://localhost/roles
Accept: application/json
